// Import Node.js Dependencies
import fs from "node:fs/promises";
import path from "node:path";
import { parseArgs } from "node:util";

// Import Third-party Dependencies
import { toStandaloneModule } from "ata-validator/build";

// Import Internal Dependencies
import {
  clientEnvelopeSchema,
  serverEnvelopeSchema
} from "../src/protocol/Envelope.schema.ts";
import type { JSONSchema } from "../src/protocol/schema.ts";

// CONSTANTS
const kProjectRoot = path.join(import.meta.dirname, "..");
const kDefaultOutDir = path.join("src", "protocol", "generated");
const kBanner = "/* eslint-disable */\n// @ts-nocheck\n// Generated by scripts/compileSchemas.ts. Do not edit.\n";
const kTargets: readonly CompileTarget[] = [
  {
    fileName: "client.compiled.ts",
    schema: clientEnvelopeSchema
  },
  {
    fileName: "server.compiled.ts",
    schema: serverEnvelopeSchema
  }
];

interface CompileTarget {
  fileName: string;
  schema: JSONSchema;
}

export function compileTarget(
  target: CompileTarget
): string {
  const module = toStandaloneModule(target.schema, {
    format: "esm",
    source: false
  });
  if (module === null) {
    throw new Error(`ata-validator declined to compile "${target.fileName}"`);
  }

  const body = module
    .split("\n")
    .filter((line) => !line.startsWith("//") && line !== "'use strict';")
    .join("\n")
    .trim();

  return `${kBanner}\n${body}\n`;
}

export function compileAll(): Map<string, string> {
  return new Map(
    kTargets.map((target) => [target.fileName, compileTarget(target)])
  );
}

async function main(): Promise<void> {
  const { values } = parseArgs({
    options: {
      "out-dir": {
        type: "string",
        default: kDefaultOutDir
      },
      check: {
        type: "boolean",
        default: false
      }
    }
  });

  const outDir = path.resolve(kProjectRoot, values["out-dir"]);
  const modules = compileAll();

  if (values.check) {
    const stale: string[] = [];
    for (const [fileName, content] of modules) {
      const current = await fs
        .readFile(path.join(outDir, fileName), "utf8")
        .catch(() => null);
      if (current !== content) {
        stale.push(fileName);
      }
    }

    if (stale.length > 0) {
      throw new Error(
        `stale compiled schemas: ${stale.join(", ")}. Run "npm run build:schemas".`
      );
    }

    return;
  }

  await fs.mkdir(outDir, { recursive: true });
  for (const [fileName, content] of modules) {
    await fs.writeFile(path.join(outDir, fileName), content);
  }
}

if (process.argv[1] === import.meta.filename) {
  await main();
}
